"""
utils/pdf_generator.py - Generate PDF ledger reports using ReportLab
"""
from __future__ import annotations
import io
import logging
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable
)

logger = logging.getLogger(__name__)


def generate_customer_statement(
    client_name: str,
    business_name: str,
    customer_name: str,
    records: list[dict],
) -> bytes:
    """
    Generate a PDF statement for one customer.
    Returns raw PDF bytes.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "title", parent=styles["Title"],
        fontSize=18, spaceAfter=4, textColor=colors.HexColor("#1a1a2e"),
    )
    sub_style = ParagraphStyle(
        "sub", parent=styles["Normal"],
        fontSize=10, textColor=colors.grey,
    )
    heading_style = ParagraphStyle(
        "heading", parent=styles["Heading2"],
        fontSize=13, textColor=colors.HexColor("#16213e"),
    )

    story = []

    # ── Header ─────────────────────────────────────────────
    story.append(Paragraph(business_name or client_name, title_style))
    story.append(Paragraph(
        f"Ledger Statement | {datetime.now().strftime('%d %B %Y')}",
        sub_style
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e0e0e0")))
    story.append(Spacer(1, 0.4*cm))

    story.append(Paragraph(f"Customer: <b>{customer_name}</b>", heading_style))
    story.append(Spacer(1, 0.4*cm))

    if not records:
        story.append(Paragraph("No records found.", styles["Normal"]))
        doc.build(story)
        return buf.getvalue()

    # ── Table ──────────────────────────────────────────────
    headers = ["Date", "Items", "Total (₹)", "Payment (₹)", "Due (₹)"]
    rows = [headers]

    for r in records:
        items_str = ", ".join(
            f"{it['name']} ₹{it['amount']:.0f}"
            for it in (r.get("items") or [])
        ) or "—"
        rows.append([
            r.get("date", ""),
            items_str,
            f"₹{float(r.get('current_total', 0)):.0f}",
            f"₹{float(r.get('payment', 0)):.0f}",
            f"₹{float(r.get('updated_due', 0)):.0f}",
        ])

    # Add summary row
    total_sales = sum(float(r.get("current_total", 0)) for r in records)
    total_paid  = sum(float(r.get("payment", 0)) for r in records)
    final_due   = float(records[-1].get("updated_due", 0)) if records else 0

    rows.append(["", "TOTAL", f"₹{total_sales:.0f}", f"₹{total_paid:.0f}", f"₹{final_due:.0f}"])

    col_widths = [2.5*cm, 7*cm, 2.5*cm, 2.8*cm, 2.5*cm]
    t = Table(rows, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        # Header
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 0), (-1, 0), 10),
        ("ALIGN",      (0, 0), (-1, 0), "CENTER"),
        # Data rows
        ("FONTSIZE",   (0, 1), (-1, -2), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -2), [colors.white, colors.HexColor("#f5f5f5")]),
        ("ALIGN",      (2, 1), (-1, -1), "RIGHT"),
        # Summary row
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#e8f4fd")),
        ("FONTNAME",   (0, -1), (-1, -1), "Helvetica-Bold"),
        # Grid
        ("GRID",       (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("VALIGN",     (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
    ]))
    story.append(t)

    story.append(Spacer(1, 0.8*cm))
    story.append(Paragraph(
        f"Generated by Digital Khata | {datetime.now().strftime('%d/%m/%Y %H:%M')}",
        ParagraphStyle("footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey)
    ))

    doc.build(story)
    return buf.getvalue()


def generate_monthly_report(
    client_name: str,
    business_name: str,
    month_label: str,
    summary: list[dict],
) -> bytes:
    """Monthly summary PDF across all customers."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(business_name or client_name,
                           ParagraphStyle("t", parent=styles["Title"], fontSize=20,
                                          textColor=colors.HexColor("#1a1a2e"))))
    story.append(Paragraph(f"Monthly Report — {month_label}",
                           ParagraphStyle("s", parent=styles["Normal"],
                                          fontSize=11, textColor=colors.grey)))
    story.append(Spacer(1, 0.5*cm))

    headers = ["Customer", "Total Sales (₹)", "Total Paid (₹)", "Pending Due (₹)"]
    rows = [headers]
    for row in summary:
        pending = max(0, row["total_sales"] - row["total_payments"])
        rows.append([
            row["customer_name"],
            f"₹{row['total_sales']:.0f}",
            f"₹{row['total_payments']:.0f}",
            f"₹{pending:.0f}",
        ])

    t = Table(rows, colWidths=[6*cm, 4*cm, 4*cm, 4*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#16213e")),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("GRID",       (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("ALIGN",      (1, 0), (-1, -1), "RIGHT"),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ]))
    story.append(t)
    doc.build(story)
    return buf.getvalue()
